# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nresp.proto\"w\n\x12\x43\x61lculationRequest\x12\x0f\n\x07wood_id\x18\x01 \x01(\x05\x12\x16\n\x0ehumidity_start\x18\x02 \x01(\x02\x12\x14\n\x0chumidity_end\x18\x03 \x01(\x02\x12\x12\n\ndryer_type\x18\x04 \x01(\x05\x12\x0e\n\x06method\x18\x05 \x01(\t\"@\n\x13\x43\x61lculationResponse\x12\x12\n\nheat_value\x18\x01 \x01(\x02\x12\x15\n\rerror_message\x18\x02 \x01(\t2]\n\x12\x43\x61lculationService\x12G\n\x18\x43\x61lculateHeatConsumption\x12\x13.CalculationRequest\x1a\x14.CalculationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CALCULATIONREQUEST']._serialized_start=14
  _globals['_CALCULATIONREQUEST']._serialized_end=133
  _globals['_CALCULATIONRESPONSE']._serialized_start=135
  _globals['_CALCULATIONRESPONSE']._serialized_end=199
  _globals['_CALCULATIONSERVICE']._serialized_start=201
  _globals['_CALCULATIONSERVICE']._serialized_end=294
# @@protoc_insertion_point(module_scope)
