# Generated by Django 4.2.3 on 2023-07-29 12:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DryerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип сушилки',
                'verbose_name_plural': 'Типы сушилок',
            },
        ),
        migrations.CreateModel(
            name='TimePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Отопительный Период',
                'verbose_name_plural': 'Отопительные периоды',
            },
        ),
        migrations.CreateModel(
            name='WoodType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Тип древесины',
                'verbose_name_plural': 'Типы древесины',
            },
        ),
        migrations.CreateModel(
            name='WoodParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_dif', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(90)], verbose_name='Wh-Wk')),
                ('heat_value', models.IntegerField(default=1, verbose_name='q ккал.кг')),
                ('dryer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irender.dryertype')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irender.timeperiod')),
                ('wood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irender.woodtype')),
            ],
            options={
                'verbose_name': 'Удельные расходы теплоты на сушку древесины',
                'verbose_name_plural': 'Удельные расходы теплоты на сушку древесины',
            },
        ),
        migrations.CreateModel(
            name='WoodCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название материала')),
                ('density', models.PositiveIntegerField(default=1, verbose_name='Плотность')),
                ('wood_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irender.woodtype')),
            ],
            options={
                'verbose_name': 'Плотность сухого материала',
                'verbose_name_plural': 'Плотности сухого материала',
            },
        ),
    ]
